version: "3"
services:
  db:
    image: "bitnami/mongodb:latest"
    ports:
      - '27017:27017'
    networks:
      - net
    environment:
      MONGODB_USERNAME: system
      MONGODB_PASSWORD: keijo1234
      MONGODB_DATABASE: adcampaign
    volumes:
      - './containers/mongo:/data/db'
networks:
  net:
